version: '2'

services:

    wiremock:
      image: rodolpheche/wiremock:2.13.0-alpine
      container_name: wiremock
      restart: always
      ports:
        - 9000:8080
      volumes:
        - ./wiremock:/home/wiremock
