@startuml
actor :User:
cloud api #LightBlue

package "Currency Exchange Service" {
    User -down-> [controller] : getRate
    [controller] -down-> [service]
    [service] -down-> [repository]
}

[repository] -> api : "                "
@enduml
